apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jankybank
  name: jankybank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jankybank
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jankybank
    spec:
      containers:
      - image: eurogig/jankybank@sha256:809caaf293b92ff06b74d09fc87fd4bd6d5c437c4a348258448b1260fbc52d7a
        name: jankybank
        ports:
        - containerPort: 8080
        resources: {}
        securityContext:
          privileged: true
        envFrom:
        - secretRef:
            name: dbsecret
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simpledeploy
  name: simpledeploy
spec:
  ports:
  - name: "30080"
    port: 30080
    nodePort: 30080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jankybank
  type: NodePort
